---
- rule:
    # data-plane PR
    paths:
      - "specification/**/data-plane/**"
    reviewers:
      - anuchandy
      - jhendrixMSFT
      - lmazuel
      - tjprescott
      
- rule:	
    paths: "specification/mediaservices/**"	
    reviewers:	
      - allenjzhang

- rule:
    # manager-plane PR
    paths:
      - "**"
    reviewers:
      - allenjzhang
      - markcowl

